### ISSUE TITLE
warning for insufficient RAM?

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/roads#2]
Could we try something like we noted before? https://github.com/degauss-org/degauss_template/issues/2

**Comment by cole-brokamp** [comment]
@erikarasnick -- we can sneak in a `dht::check_ram(4)` ?  do you think 4GB of RAM is enough for most tasks?

**Comment by erikarasnick** [comment]
Yes, I think so... I know that's what it takes to merge in census tracts in the geocoder. Should this go in the code where we do other dht checks, like the column name checks?

**Comment by cole-brokamp** [comment]
yes, I was thinking right after a `greeting()`.  but we will wait to implement it until we know exactly how much ram we would end up recommending, which will likely change with our speed updates in #3

**Comment by erikarasnick** [comment]
closed in #4
